import matplotlib.pyplot as plt
import csv

print("Plotter: Reading 2D path coordinates...")
x_coords, y_coords, ids = [], [], []

# Read from the coordinate file generated by your C++ program
with open('final_path_coordinates.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader)  # Skip header
    for row in reader:
        vid = int(row[0])
        x, y = float(row[1]), float(row[2])
        ids.append(vid)
        x_coords.append(x)
        y_coords.append(y)

if not x_coords:
    print("Plotter: No path data found!")
    exit()

# --- 2D Plot ---
fig, ax = plt.subplots(figsize=(12, 10))
ax.plot(x_coords, y_coords, 'b-', linewidth=1.5, label='Path')
ax.scatter(x_coords, y_coords, color='black', s=10)

# Draw arrows for direction
for i in range(len(x_coords) - 1):
    dx = x_coords[i+1] - x_coords[i]
    dy = y_coords[i+1] - y_coords[i]
    ax.arrow(x_coords[i], y_coords[i], dx, dy,
             head_width=1.0, head_length=2.0, fc='orange', ec='orange', alpha=0.7)

# Label each waypoint with its ID
for i, vid in enumerate(ids):
    ax.text(x_coords[i], y_coords[i], str(vid), fontsize=7, color='purple')

# Start & End points
ax.scatter(x_coords[0], y_coords[0], color='green', s=100, label='Start', zorder=5)
ax.scatter(x_coords[-1], y_coords[-1], color='red', s=100, label='End', zorder=5)

ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.set_title('2D Drone Traversal Path (Top-Down View)')
ax.legend()
ax.grid(True)
ax.axis('equal')  # Keeps aspect ratio same for X and Y
plt.tight_layout()
plt.show()
